# db 패키지 — Supabase repository 모음
# 각 모듈을 직접 import해서 사용:
#   from db.doc_chunk_repo import ...
#   from db.doc_metadata_repo import ...
#   from db.qa_generation_repo import ...
#   from db.evaluation_repo import ...
#   from db.dashboard_repo import ...
# (외부 코드는 config.supabase_client re-export wrapper를 통해 접근)
